### ISSUE TITLE
language inconsistency

### ISSUE THREAD

**Issue by ax-sc** [desklab/desklab-arduino-lib#6]
We are incosistent in the language(s) which we are using in this repository. Some parts of the code/comments are in German (including the name of some methods), documentation (when existing) is mostly in English, Licenses and further information even mix those. Before expanding this library we should come up with some standards about when to use which language.

To make it more concrete, this are (at least some of) the issues/files which may be affected or should be addressed:

- [x] example sketches (EN) 
    - [./examples](https://github.com/desklab/desklab-arduino-lib/tree/master/examples)
- [x] Readme (EN) 
    - [./README.md](https://github.com/desklab/desklab-arduino-lib/blob/master/README.md)
- [x] sourcecode of examples (DE) 
    - [./examples/.../PhotometerAdvanced.ino](https://github.com/desklab/desklab-arduino-lib/blob/master/examples/PhotometerAdvanced/PhotometerAdvanced.ino)
    - [./examples/.../PhotometerDetailed.ino](https://github.com/desklab/desklab-arduino-lib/blob/master/examples/PhotometerDetailed/PhotometerDetailed.ino)
    - [./examples/.../PhotometerShort.ino](https://github.com/desklab/desklab-arduino-lib/blob/master/examples/PhotometerShort/PhotometerShort.ino)
- [x] comments with additional information in library files (DE/EN)
    - [./src/desklab.cpp](https://github.com/desklab/desklab-arduino-lib/blob/729b70f88242224a1446186d44d8ef8ed05ced88/src/desklab.cpp#L1-L29)
    - [./src/desklab.h](https://github.com/desklab/desklab-arduino-lib/blob/729b70f88242224a1446186d44d8ef8ed05ced88/src/desklab.h#L1-L29)

I would suggest following these criteria:
1. Source code is written in EN. This includes documentation inside library-files, filenames (inlcluding examples) and designation of methods.
2. Comments in examples are written in DE. 
3. Readme and conversation in issues/projects/actions/pull requests is in EN. (We could think about providing an additional Readme in DE?)

Moving to EN method-names shouldn´t be a problem for most of the users as we only provide basic methods (like `read`, `print`,...). Using EN consistently in those files of the library pupils are unlikely to see shouldn´t be problematic either, as those, who will open these files, are likely to be capable of working with code in EN. For backward-compatibility we should keep the German method-names as wrappers around the new ones but drop them from our teaching documents now before removing them from the code sometime in the future.

**Comment by 3j14** [comment]
I agree with most of your points 👍🏽 
Are you suggesting to use English function names going forward? I think we should stick with German function names and even new functions should continue to be German. Changing this could lead to confusion with teachers and students. Maybe offer both, e.g. functions are mapped from English to German in the header file (also for new functions not yet introduced):

```c
double PhotometerReadSensor(int sensorPin);
double PhotometerSensorAuslesen(int sensorPin) = PhotometerReadSensor;
```

But then we have to be consistent with what we state in our teaching documents. I think sticking with German for the teaching documents would be beneficial.

**Comment by ax-sc** [comment]
Yes, that´s what i thought of. Offering both (for some transition time) is perfectly fine to me and what i meant with:

> For backward-compatibility we should keep the German method-names as wrappers around the new ones but drop them from our teaching documents now before removing them from the code sometime in the future.

When considering possible confusion i would (at a first glance) agree with sticking with the German function names but the argument of teachers and pupils getting used to them doesn´t improve over the time and i still think we are able to handle this change at the moment. 

Being in a line with other libraries pupils possibly use in their lessons seems to me more important than avoiding the impact of this change for a short term. You are completely right that this has to be accompanied by changing our teaching documents, but this shouldn´t be a problem once the code is refactored. Thinking about your point of offering both versions (without deprecating the German one) for a long term I`m afraid that this would lead to even more confusion given that both are "correct" and teachers then are expected to be aware of both, maybe also needing to have all teaching documents in multiple versions at their hands.

**Comment by charliieee** [comment]
> Thinking about your point of offering both versions (without deprecating the German one) for a long term I`m afraid that this would lead to even more confusion given that both are "correct" and teachers then are expected to be aware of both, maybe also needing to have all teaching documents in multiple versions at their hands.

Good point, I agree. Do you remember the set-up of circuit A and circuit B? This produces too many versions of documents.

**Comment by 3j14** [comment]
Alright, got it! Sounds good.
Yeah, on the long term we should provide only one version to avoid confusion.
Also, is there some sort of code style guide from Arduino? Using capitalised function names confuses me personally because in most programming languages I would associate an capitalised name with an object.

**Comment by ax-sc** [comment]
> Also, is there some sort of code style guide from Arduino? Using capitalised function names confuses me personally because in most programming languages I would associate an capitalised name with an object.

see https://www.arduino.cc/en/Reference/APIStyleGuide 

> **Use full, everyday words.** Don’t be terse with your function names or variables. Use everyday terms instead of technical ones. Pick terms that correspond to popular perception of the concept at hand. Don’t assume specialized knowledge. For example, this is why we used analogWrite() rather than pwm(). Abbreviations are acceptable, though, if they’re in common use or are the primary name for something.For example, “HTML” is relatively common and “SPI” is effectively the name of that protocol (“serial-peripheral interface” is probably too long). (“Wire” was probably a mistake, as the protocol it uses is typically called “TWI” or “I2C”.) 

> **Use the established core libraries and styles.**
> Use read() to read inputs, and write() to write to outputs, e.g. digitalRead(), analogWrite(), etc.
> Use the Stream.h and Print.h libraries when dealing with byte streams. If it’s not appropriate, at least try to use its API as a model. For more on this, see below
> For network applications, use the Client and Server libraries as the basis.
> Use begin() to initialize a library instance, usually with some settings. Use end() to stop it. 
> 
> **Use camel case function names, not underscore.** For example, analogRead, not analog_read. Or myNewFunction, not my_new_function. We've adopted this from Processing.org for readability's sake.
> 
> **LONG_CONSTANT_NAMES_FULL_OF_CAPS** are hard to read. Try to simplify when possible, without being terse
